#!/usr/bin/env python3
"""AUTO-520: render every generated artifact from validated Git intent.

Renders the Ansible inventory and the Python engine's device configurations
(ADR 0019) into one directory. Every file starts with a header naming its
generator and source. Rendering is pure and deterministic: ``--check`` renders
twice into separate directories, requires identical bytes, and requires the
tracked ``automation/inventory/hosts.yml`` to be current.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
INVENTORY = ROOT / "inventory" / "inventory.yaml"
DEFAULT_OUTPUT = ROOT / "artifacts" / "render"
HOSTS = ROOT / "automation" / "inventory" / "hosts.yml"
GENERATOR = "automation/render/render_all.py"


def _module(relative: str, name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, ROOT / relative)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str((ROOT / relative).parent))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.pop(0)
    return module


def _header(comment: str, source: str) -> str:
    return f"{comment} Generated by {GENERATOR} ({source}) from inventory/inventory.yaml; do not edit.\n"


def render(data: dict[str, Any]) -> dict[str, str]:
    """Relative path -> file content for every generated artifact."""
    files: dict[str, str] = {}

    def add(path: str, comment: str, source: str, content: str) -> None:
        files[path] = _header(comment, source) + content

    inventory = _module("automation/inventory/render_inventory.py", "netlab_render_inventory")
    files["inventory/hosts.yml"] = inventory.render_yaml(data)

    ospf = _module("config/routing/ospf/render.py", "netlab_ospf_render")
    for node, text in sorted(ospf.configs(data).items()):
        add(f"frr/ospf/{node}.conf", "!", "config/routing/ospf/render.py", text)
    bgp = _module("config/routing/bgp/render.py", "netlab_bgp_render")
    for node, text in sorted(bgp.configs(data).items()):
        add(f"frr/bgp/{node}.conf", "!", "config/routing/bgp/render.py", text)

    security = _module("config/security/apply.py", "netlab_security_apply")
    for node, tables in sorted(security.render_plan(data).items()):
        for family, text in sorted(tables.items()):
            add(f"nftables/{node}-{family}.nft", "#", "config/security/apply.py", text)

    ipsec = _module("config/ipsec/apply.py", "netlab_ipsec_apply")
    for peer in sorted(ipsec.build_plan(data)["peers"], key=lambda p: (p["node"], p["connection"])):
        add(f"swanctl/{peer['node']}/{peer['connection']}.conf", "#",
            "config/ipsec/apply.py", peer["swanctl_config"])

    gateway = _module("config/gateway/apply.py", "netlab_gateway_apply")
    for item in sorted(gateway.build_plan(data)["nodes"], key=lambda n: n["node"]):
        add(f"keepalived/{item['node']}.conf", "#", "config/gateway/apply.py", item["keepalived_config"])

    switching = _module("config/switching/apply.py", "netlab_switching_apply")
    plan = switching.build_plan(data)
    add("ovs/switching-plan.json", "//", "config/switching/apply.py",
        json.dumps(plan, indent=2, sort_keys=True, default=str) + "\n")
    return files


def write(files: dict[str, str], output: Path) -> None:
    for relative, content in sorted(files.items()):
        path = output / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def digest(output: Path) -> dict[str, str]:
    return {
        path.relative_to(output).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(output.rglob("*"))
        if path.is_file()
    }


def check(data: dict[str, Any]) -> list[str]:
    problems: list[str] = []
    with tempfile.TemporaryDirectory() as first, tempfile.TemporaryDirectory() as second:
        write(render(data), Path(first))
        write(render(data), Path(second))
        a, b = digest(Path(first)), digest(Path(second))
        if a != b:
            problems.append(f"render is not deterministic: {sorted(set(a.items()) ^ set(b.items()))[:5]}")
        for relative in a:
            head = (Path(first) / relative).read_text(encoding="utf-8").splitlines()[0]
            if "Generated by" not in head:
                problems.append(f"{relative} does not identify its generator")
        rendered_hosts = (Path(first) / "inventory" / "hosts.yml").read_text(encoding="utf-8")
    if not HOSTS.is_file() or HOSTS.read_text(encoding="utf-8") != rendered_hosts:
        problems.append(f"{HOSTS.relative_to(ROOT).as_posix()} is stale; run make render")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(INVENTORY.read_text(encoding="utf-8"))
    if args.check:
        problems = check(data)
        for problem in problems:
            print(f"render check: {problem}", file=sys.stderr)
        print("render check: " + ("FAIL" if problems else "PASS (deterministic, headers, hosts.yml current)"))
        return 1 if problems else 0
    files = render(data)
    write(files, args.output)
    HOSTS.write_text(files["inventory/hosts.yml"], encoding="utf-8", newline="\n")
    print(f"rendered {len(files)} files to {args.output}; updated {HOSTS.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
