@version: 4.0
options { chain_hostnames(no); keep_hostname(yes); use_dns(no); };
source s_network { syslog(transport("udp") ip("172.31.255.14") port(514)); syslog(transport("tcp") ip("172.31.255.14") port(514)); };
destination d_netlab { file("/var/log/netlab/syslog.log" template("${ISODATE} ${HOST} ${PROGRAM}[${PID}]: ${MSG}\n") owner("root") perm(0640) dir-perm(0750) create-dirs(yes)); };
log { source(s_network); destination(d_netlab); flags(flow-control); };
