#!/usr/bin/env python3
"""AUTO-520: Ansible inventory from validated Git intent (ADR 0019).

``build(hosts)`` turns a host list into the inventory structure, so the static
inventory (from Git) and the NetBox dynamic inventory (netbox_inventory.py)
share one shape and can be compared directly.
"""

from __future__ import annotations

import ipaddress
import json
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
INVENTORY = ROOT / "inventory" / "inventory.yaml"
LAB = "netlab-phase-1"
SHARED_SITE = "shared"
HEADER = (
    "# Generated by automation/inventory/render_inventory.py from "
    "inventory/inventory.yaml (via make render); do not edit.\n"
)


def host(name: str, role: str, site: str | None, oob: str | None) -> dict[str, Any]:
    return {
        "name": name,
        "netlab_role": role,
        "netlab_site": site or SHARED_SITE,
        "netlab_container": f"clab-{LAB}-{name}",
        "netlab_oob": str(ipaddress.ip_interface(oob).ip) if oob else None,
    }


def hosts_from_intent(data: dict[str, Any]) -> list[dict[str, Any]]:
    return [host(n["id"], n["role"], n.get("site"), n.get("oob")) for n in data["nodes"]]


def build(hosts: list[dict[str, Any]]) -> dict[str, Any]:
    """Ansible YAML inventory: host vars under all.hosts, role_* and site_* groups."""
    children: dict[str, dict[str, Any]] = {}
    for item in hosts:
        for group in (f"role_{item['netlab_role']}", f"site_{item['netlab_site']}"):
            children.setdefault(group, {"hosts": {}})["hosts"][item["name"]] = None
    return {
        "all": {
            "vars": {
                "ansible_connection": "local",
                "ansible_python_interpreter": "{{ ansible_playbook_python }}",
                "netlab_lab": LAB,
            },
            "hosts": {
                item["name"]: {k: v for k, v in item.items() if k != "name"}
                for item in sorted(hosts, key=lambda h: h["name"])
            },
            "children": {name: children[name] for name in sorted(children)},
        }
    }


def render_yaml(data: dict[str, Any]) -> str:
    body = yaml.safe_dump(build(hosts_from_intent(data)), sort_keys=True, default_flow_style=False)
    return HEADER + body


def main() -> int:
    data = json.loads(INVENTORY.read_text(encoding="utf-8"))
    sys.stdout.write(render_yaml(data))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
