#!/usr/bin/env python3
"""Render Phase 1 FRR BGP configuration from the authoritative inventory."""

from __future__ import annotations

import argparse
import ipaddress
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
INVENTORY = ROOT / "inventory" / "inventory.yaml"
PHYSICAL_LINK_KINDS = {"routed", "ebgp", "l2", "access"}


def load_inventory(path: Path = INVENTORY) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    sites = {site["id"]: site for site in data["sites"]}
    if set(sites) != {"hq", "br1"}:
        raise ValueError("WAN-140 requires exactly the Phase 1 sites hq and br1")
    isps = [node for node in data["nodes"] if node.get("role") == "isp" and node["asn"] == 65000]
    if len(isps) != 1 or isps[0]["id"] != "isp1-core-1":
        raise ValueError("WAN-140 requires ISP-1 isp1-core-1 in AS 65000")
    return data


def _ip(address: str) -> str:
    return str(ipaddress.ip_interface(address).ip)


def _peer(data: dict[str, Any], site_id: str) -> tuple[int, str, str]:
    node_id = {"hq": "hq-edge-1", "br1": "br1-edge-1"}[site_id]
    edge = next(node for node in data["nodes"] if node["id"] == node_id)
    link = next(link for link in data["links"] if link["kind"] == "ebgp" and any(
        endpoint["node"] == node_id for endpoint in link["endpoints"]
    ))
    local = next(endpoint for endpoint in link["endpoints"] if endpoint["node"] == node_id)
    remote = next(endpoint for endpoint in link["endpoints"] if endpoint["node"] != node_id)
    return edge["asn"], _ip(local["address"]), _ip(remote["address"])


def _underlay_interfaces(data: dict[str, Any], node_id: str) -> list[str]:
    node = next(node for node in data["nodes"] if node["id"] == node_id)
    mapping = {
        interface["name"]: f"eth{index}"
        for index, interface in enumerate(
            (interface for interface in node.get("interfaces", []) if interface.get("kind") in PHYSICAL_LINK_KINDS),
            start=1,
        )
    }
    lines: list[str] = []
    for link in data["links"]:
        if link["kind"] != "ebgp":
            continue
        local = next((endpoint for endpoint in link["endpoints"] if endpoint["node"] == node_id), None)
        if local is None:
            continue
        peer = next(endpoint for endpoint in link["endpoints"] if endpoint["node"] != node_id)
        interface = mapping[local["interface"]]
        peer_name = peer["node"].replace("-", "_")
        description = f"to_{peer_name}_{peer['interface']}"
        lines.extend([
            f"interface {interface}",
            f" description {description}",
            f" ip address {local['address']}",
            "!",
        ])
    return lines


def configs(data: dict[str, Any]) -> dict[str, str]:
    sites = {site["id"]: site for site in data["sites"]}
    isp = next(node for node in data["nodes"] if node.get("role") == "isp")
    endpoints = sorted(_ip(site["public_endpoint"]) + "/32" for site in data["sites"])
    isp_router_id = _ip(isp["interfaces"][0]["addresses"][0])
    result: dict[str, str] = {}
    isp_lines = [
        "! Generated by config/routing/bgp/render.py from inventory/inventory.yaml; do not edit.",
        *_underlay_interfaces(data, isp["id"]),
        "ip route 0.0.0.0/0 Null0",
        "ip route 203.0.113.0/25 Null0",
    ]
    isp_lines.extend([
        f"ip prefix-list SITE-ENDPOINTS seq {sequence * 10} permit {endpoint}"
        for sequence, endpoint in enumerate(endpoints, start=1)
    ])
    isp_lines.extend([
        "ip prefix-list SITE-ENDPOINTS seq 100 deny 0.0.0.0/0 le 32",
        "ip prefix-list ISP-DEFAULT-ONLY seq 10 permit 0.0.0.0/0",
        "ip prefix-list ISP-DEFAULT-ONLY seq 100 deny 0.0.0.0/0 le 32",
        "router bgp 65000",
        f" bgp router-id {isp_router_id}",
        " no bgp ebgp-requires-policy",
    ])
    for site_id in ("hq", "br1"):
        asn, peer_ip, _ = _peer(data, site_id)
        isp_lines.extend([
            f" neighbor {peer_ip} remote-as {asn}",
            f" neighbor {peer_ip} description {site_id.upper()}-EDGE-1",
            f" neighbor {peer_ip} maximum-prefix 1",
            f" neighbor {peer_ip} default-originate",
            f" neighbor {peer_ip} prefix-list SITE-ENDPOINTS in",
            f" neighbor {peer_ip} prefix-list ISP-DEFAULT-ONLY out",
        ])
    isp_lines.append(" address-family ipv4 unicast")
    for site_id in ("hq", "br1"):
        _, peer_ip, _ = _peer(data, site_id)
        isp_lines.append(f"  neighbor {peer_ip} activate")
    isp_lines.extend([" exit-address-family", "!"])
    result[isp["id"]] = "\n".join(isp_lines) + "\n"

    for site_id, node_id in (("hq", "hq-edge-1"), ("br1", "br1-edge-1")):
        site = sites[site_id]
        _, _, peer_ip = _peer(data, site_id)
        endpoint = site["public_endpoint"]
        router_id = _ip(next(node for node in data["nodes"] if node["id"] == node_id)["loopback"])
        prefix_name = "ISP-DEFAULT"
        lines = _underlay_interfaces(data, node_id) + [
            "! Generated by config/routing/bgp/render.py from inventory/inventory.yaml; do not edit.",
            f"ip route {endpoint} Null0",
            f"ip prefix-list {prefix_name} seq 10 permit 0.0.0.0/0",
            f"ip prefix-list {prefix_name} seq 100 deny 0.0.0.0/0 le 32",
            f"ip prefix-list {site_id.upper()}-ENDPOINT seq 10 permit {endpoint}",
            f"ip prefix-list {site_id.upper()}-ENDPOINT seq 100 deny 0.0.0.0/0 le 32",
            "route-map ISP-IN permit 10",
            f" match ip address prefix-list {prefix_name}",
            f"route-map {site_id.upper()}-OUT permit 10",
            f" match ip address prefix-list {site_id.upper()}-ENDPOINT",
            f"route-map {site_id.upper()}-OUT deny 100",
            f"router bgp {site['asn']}",
            f" bgp router-id {router_id}",
            " no bgp ebgp-requires-policy",
            f" neighbor {peer_ip} remote-as 65000",
            " neighbor {} description ISP1-CORE-1".format(peer_ip),
            f" neighbor {peer_ip} maximum-prefix 1",
            f" neighbor {peer_ip} prefix-list {prefix_name} in",
            f" neighbor {peer_ip} prefix-list {site_id.upper()}-ENDPOINT out",
            " address-family ipv4 unicast",
            f"  neighbor {peer_ip} activate",
            f"  neighbor {peer_ip} route-map ISP-IN in",
            f"  neighbor {peer_ip} route-map {site_id.upper()}-OUT out",
            f"  network {endpoint}",
            " exit-address-family",
            "!",
        ]
        result[node_id] = "\n".join(lines) + "\n"
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", type=Path, default=INVENTORY)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    for node_id, content in configs(load_inventory(args.inventory)).items():
        path = args.output_dir / f"{node_id}.conf"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"rendered {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
