#!/usr/bin/env python3
"""AUTO-510: generate NetBox runtime secrets once (idempotent, never committed).

Writes artifacts/netbox/netbox.env (mode 0600) for services/netbox/compose.yaml.
An existing file is kept, so repeated runs do not rotate credentials.
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ENV_FILE = ROOT / "artifacts" / "netbox" / "netbox.env"


def render() -> str:
    db_password = secrets.token_urlsafe(24)
    redis_password = secrets.token_urlsafe(24)
    values = {
        # PostgreSQL container
        "POSTGRES_DB": "netbox",
        "POSTGRES_USER": "netbox",
        "POSTGRES_PASSWORD": db_password,
        # NetBox container (netbox-docker variables)
        "DB_HOST": "postgres",
        "DB_NAME": "netbox",
        "DB_USER": "netbox",
        "DB_PASSWORD": db_password,
        "REDIS_HOST": "redis",
        "REDIS_PASSWORD": redis_password,
        "REDIS_CACHE_HOST": "redis",
        "REDIS_CACHE_PASSWORD": redis_password,
        "SECRET_KEY": secrets.token_urlsafe(64),
        "SKIP_SUPERUSER": "false",
        "SUPERUSER_NAME": "netlab",
        "SUPERUSER_EMAIL": "netlab@example.invalid",
        "SUPERUSER_PASSWORD": secrets.token_urlsafe(24),
        "SUPERUSER_API_TOKEN": secrets.token_hex(20),
        "ALLOWED_HOSTS": "127.0.0.1 localhost",
    }
    lines = [f"{key}={value}" for key, value in values.items()]
    return "# Generated by automation/netbox/prepare.py; local only, never commit.\n" + "\n".join(lines) + "\n"


def main() -> int:
    if ENV_FILE.is_file():
        print(f"kept existing {ENV_FILE.relative_to(ROOT).as_posix()}")
        return 0
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text(render(), encoding="utf-8")
    os.chmod(ENV_FILE, 0o600)
    print(f"generated {ENV_FILE.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
